### ISSUE TITLE
Docker build fails in 2024

### ISSUE THREAD

**Issue by telatin** [nicokist/RNASeq_similarity_matrix#5]
💻  Command:
```bash
docker build RNASeq_similarity_matrix -t rnaseq_similarity_matrix
```

Fails at step 16/25:

📄  Log:
```text
Step 16/25 : RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51716619E084DAB9
 ---> Running in a59e82e00437
Executing: /tmp/tmp.EwzTktIYFj/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
51716619E084DAB9
gpg: requesting key E084DAB9 from hkp server keyserver.ubuntu.com
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
The command '/bin/sh -c apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51716619E084DAB9' returned a non-zero code: 2
```

I noted that the packages installed via `apt-get` are not pinned to a specific version, and as time goes by this could generate different packages than initially planned?

Thanks for the support! Have a good day

**Comment by bkbonde** [comment]
Hi there 
looking at your error its related to key server timeout.
> gpg: keyserver timed out
> gpg: keyserver receive failed: keyserver error

so it seems some of the key server is not reachable. I will try to reproduce at my end to see to see if I can send you fix

**Comment by telatin** [comment]
Thanks a million!

**Comment by nicokist** [comment]
Thanks for your bug report @telatin, and for your prompt response @bkbonde, hope you're keeping well.

I was able to build the image without making changes. Is it possible your [firewall blocks port 11371](https://unix.stackexchange.com/questions/75892/keyserver-timed-out-when-trying-to-add-a-gpg-public-key)?


Could you try changing the line in Dockerfile
`RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51716619E084DAB9`

to 

`RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 51716619E084DAB9`

**Comment by telatin** [comment]
Thanks will try. I temporarily patched with `RUN apt-get install -y --allow-unauthenticated r-base r-base-dev bcftools` and that worked too

**Comment by nicokist** [comment]
Awesome, let us know how you get on!

**Comment by bkbonde** [comment]
also going forward it will be good to keep things backward compatible: 
we can fix it at following places:
1) Ubuntu image -> 16.04 is really old -> please use 22.04 which is LTS supported release and most updated in terms of security
2) use R version (4.3.2) with stable repo of Debian bullseye : 
   change line 23 of docker file : > RUN add-apt-repository "deb http://cloud.r-project.org/bin/linux/debian bullseye-cran40/"
 3) update the key : 
 line 24 of docker file :   gpg --keyserver keyserver.ubuntu.com --recv-key '95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7'
 
 this will make the implementation more stable and robust

**Comment by bkbonde** [comment]
Issue is closed : if you need help please reopen or create new bug report
